# Generated by Django 4.0.8 on 2023-03-09 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=60, unique=True)),
                ('user_password', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('user_public_leaf_count', models.BigIntegerField()),
                ('user_private_leaf_count', models.BigIntegerField()),
                ('user_experience_points', models.BigIntegerField()),
                ('user_verified', models.BooleanField(default=False)),
                ('user_followers', models.BigIntegerField(default=0)),
                ('user_following', models.BigIntegerField(default=0)),
                ('user_level', models.BigIntegerField(default=1)),
                ('user_universal_likes', models.BigIntegerField(default=0)),
                ('user_universal_dislikes', models.BigIntegerField(default=0)),
                ('user_universal_comments', models.BigIntegerField(default=0)),
                ('previous_experience_generation_date', models.DateTimeField(default=datetime.datetime(2023, 3, 9, 10, 53, 48, 736786))),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='master', to='user_engine.userprofile')),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='slave', to='user_engine.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 3, 9, 10, 53, 48, 737265))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='holy', to='user_engine.userprofile')),
            ],
        ),
    ]
