# Generated by Django 4.0.8 on 2022-11-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=60)),
                ('user_password', models.CharField(max_length=30)),
                ('user_id', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('user_public_leaf_count', models.BigIntegerField()),
                ('user_private_leaf_count', models.BigIntegerField()),
                ('user_experience_points', models.BigIntegerField()),
                ('user_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
