# Generated by Django 4.0.8 on 2023-03-09 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesstoken',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 15, 30, 57, 502577)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='previous_experience_generation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 15, 30, 57, 502286)),
        ),
    ]
