# Generated by Django 4.0.8 on 2023-01-15 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesstoken',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 9, 43, 25, 395536)),
        ),
    ]
