# Generated by Django 4.0.8 on 2023-01-19 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_engine', '0004_alter_useraccesstoken_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesstoken',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 6, 43, 57, 324523)),
        ),
    ]
