# Generated by Django 4.2.3 on 2023-08-19 13:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user_engine", "0004_alter_useraccesstoken_creation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfollowrequests",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="useraccesstoken",
            name="creation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 19, 13, 10, 49, 971158)
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="previous_experience_generation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 19, 13, 10, 49, 970505)
            ),
        ),
    ]
