# Generated by Django 4.0.8 on 2023-03-08 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_engine', '0005_alter_useraccesstoken_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_universal_comments',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_universal_dislikes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_universal_likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccesstoken',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 8, 21, 57, 842321)),
        ),
    ]
