# Generated by Django 4.0.8 on 2023-03-08 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_engine', '0007_alter_useraccesstoken_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesstoken',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 8, 57, 39, 403895)),
        ),
        migrations.AlterField(
            model_name='useraccesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holy', to='user_engine.userprofile'),
        ),
    ]
