# Generated by Django 4.2.3 on 2023-08-14 13:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_engine", "0004_alter_useraccesstoken_creation_date_and_more"),
        ("leaf_engine", "0003_alter_leaf_previous_analytics_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotedLeafs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("expiry", models.DateTimeField()),
                (
                    "boost_multiplier",
                    models.DecimalField(decimal_places=5, default=1, max_digits=5),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promoted_by",
                        to="user_engine.userprofile",
                    ),
                ),
                (
                    "leaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promoted_leaf",
                        to="leaf_engine.leaf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Advertisements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "target_topic_id",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(default=-1), size=None
                    ),
                ),
                ("target_topic_category", models.IntegerField(max_length=3)),
                ("advertisement_tier", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_created_by",
                        to="user_engine.userprofile",
                    ),
                ),
                (
                    "leaf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertisement",
                        to="leaf_engine.leaf",
                    ),
                ),
            ],
        ),
    ]
