# Generated by Django 4.0.8 on 2023-01-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_engine', '0002_alter_useraccesstoken_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.CharField(max_length=400)),
                ('leaf_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image_content', models.ImageField(upload_to='')),
                ('likes_count', models.BigIntegerField(default=0)),
                ('comments_count', models.BigIntegerField(default=0)),
                ('leaf_type', models.CharField(choices=[('public', 'public'), ('private', 'private')], max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to='user_engine.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeafLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_comment_leaf', to='leaf_engine.leaf')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='liked_user', to='user_engine.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeafComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commented_user', to='user_engine.userprofile')),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_leaf', to='leaf_engine.leaf')),
            ],
        ),
    ]
