# Generated by Django 4.0.8 on 2023-03-09 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaf_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='previous_analytics_run',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 10, 54, 57, 277875)),
        ),
    ]
