# Generated by Django 4.0.8 on 2023-03-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_engine', '0006_userprofile_user_universal_comments_and_more'),
        ('leaf_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaf',
            name='dilikes_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LeafDisLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disliked_user', to='user_engine.userprofile')),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_leaf', to='leaf_engine.leaf')),
            ],
        ),
    ]
