# Generated by Django 4.2.3 on 2023-08-16 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaf_engine", "0002_alter_leaf_previous_analytics_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaf",
            name="previous_analytics_run",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 16, 11, 0, 34, 739656)
            ),
        ),
    ]
