# Generated by Django 4.0.8 on 2023-03-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_engine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateLeaf',
        ),
        migrations.DeleteModel(
            name='PublicLeaf',
        ),
    ]
